# Generated by Django 5.0.3 on 2024-04-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_registry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
