# Generated by Django 5.0.3 on 2024-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_registry_app', '0002_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
